authors:
  fhiegel:
    name: Fabien HIEGEL
    description: Knowledge worker
    avatar: /assets/authors/fhiegel.jpeg
  mbonnot:
    name: Matthieu BONNOT
    description: Knowledge worker
    avatar: /assets/mbonnot.png
  jchauvin:
    name: Jérémy CHAUVIN
    description: Knowledge worker
    avatar: /assets/jchauvin.jpeg