authors:
  fhiegel:
    name: Fabien HIEGEL
    description: Knowledge worker
    avatar: assets/authors/fhiegel.png
  mbonnot:
    name: Matthieu BONNOT
    description: ""
    avatar: assets/authors/undefined.png
  jchauvin:
    name: Jérémy CHAUVIN
    description: ""
    avatar: assets/authors/undefined.png
  jpiazzalungalerat:
    name : Joël Piazzalunga-Lerat
    description: ""
    avatar: assets/authors/undefined.png
