# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# Project information
site_name: Shodo Code Retreat
site_url: https://shodo-nantes.github.io/code-retreat/
site_description: >
  Ressources pour les "Code Retreat" de Shodo Nantes
repo_url: https://github.com/shodo-nantes/code-retreat
edit_uri: ""

# Navigation
nav:
  - Code Retreat:
    - index.md
  - Événements:
    - events/index.md
  - Katas:
      - katas/game-of-life/index.md
      - katas/sailboat/index.md
      - katas/ugly-trivia/index.md
      - katas/mars-rover/index.md
  - Contraintes:
      - constraints/index.md
      - 🖥️ Sur le code:
        - 🚥 TDD:
          - constraints/tdd/index.md
          - constraints/tdd/as-if-you-meant-it.md
          - constraints/tdd/outside-in.md
          - constraints/tcr/index.md
        - constraints/refactoring/index.md
        - constraints/no-if/index.md
        - constraints/no-primitives/index.md
        - constraints/immutable-code/index.md
        - constraints/tell-dont-ask/index.md
        - constraints/everything-is-a-function/index.md
        - constraints/code-swap/index.md
        - constraints/no-mouse/index.md
      - 🙋 Sur les interactions sociales:
        - constraints/regle-du-oui/index.md
        - 2️⃣ A deux:
          - constraints/pair-programming/index.md
          - constraints/pair-programming/strong-style.md
          - constraints/pair-programming/ping-pong.md
          - constraints/pair-programming/silent.md
        - ✳️ A plusieurs :
          - constraints/mob-programming/index.md
          - constraints/mob-programming/blind-navigator.md
          - constraints/mob-programming/mute-mobbers.md
        - constraints/cross-arms/index.md
        - constraints/many-more-much-smaller-steps/index.md
not_in_nav: |
  tags.md
  slides*

# Theme options ef2929, d52929

# Configuration
theme:
  name: material
  custom_dir: theme
  language: fr
  logo: assets/images/icon-128x128.png
  favicon: assets/images/favicon.png
  features:
    - content.tabs.link
    # - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    primary: black
    accent: red

# Extra
extra_css:
  - assets/css/extra.css

extra:
  reveal:
    path: reveal.js/dist
    transition: slide
    theme:
      name: white.css
      path: theme
    plugin:
      path: reveal.js/plugin
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shodo-nantes
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Shodo_Nantes
      name: Shodo_Nantes on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/shodo-nantes/
      name: Shodo Nantes on LinkedIn

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - blog:
      blog_dir: events
      blog_toc: true
      post_dir: "{blog}/past"
  - include-markdown